#!/bin/sh
set -e
    CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt|\.java/ { print $2}')"

    if [ -z "$CHANGED_FILES" ]; then
        echo "No staged source files."
        exit 0
    fi;

    echo "Running spotless over these files:"
    echo "$CHANGED_FILES"

    ./gradlew --quiet spotlessApply -PinternalKtlintGitFilter="$CHANGED_FILES"

    echo "Completed spotless run."
    echo "$CHANGED_FILES" | while read -r file; do
    if [ -f $file ]; then
        git add $file
    fi
done
    echo "Completed spotless hook."
